# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117RcPgp6ztHzMMJWFv_MeH3lRqkCtXHa
"""

import streamlit as st
import joblib
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Load model and vectorizer
model = joblib.load("fake_news_model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

# Clean text
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+|[^a-z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return ' '.join([word for word in text.split() if word not in stop_words])

# Web UI
st.set_page_config(page_title="Fake News Detector", page_icon="📰", layout="centered")
st.title("📰 Fake News Detector")

input_text = st.text_input("Enter a news headline:")

if st.button("Check News"):
    if input_text:
        cleaned = clean_text(input_text)
        vectorized = vectorizer.transform([cleaned])
        prediction = model.predict(vectorized)

        if prediction == 0:
            st.error("❌ Uh-oh! It's Fake News! 😱")
        else:
            st.success("✅ Yay! It's Real News! 🥳")
    else:
        st.warning("⚠️ Please enter something.")